<?php

/******************************************************************************
 *
 * Purpose: result file for display of queries
 * Author:  Armin Burger
 *
 ******************************************************************************
 *
 * Copyright (c) 2003-2006 Armin Burger
 *
 * This file is part of p.mapper.
 *
 * p.mapper is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version. See the COPYING file.
 *
 * p.mapper is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with p.mapper; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 ******************************************************************************/

// prevent XSS
if (isset($_REQUEST['PM_INCPHP'])) exit();

session_start();
require_once($_SESSION['PM_INCPHP'] . "/common.php");
require_once($_SESSION['PM_INCPHP'] . "/globals.php");

$PM_JSFILES_TOLOAD = array("common.js", "sorttable.js", "custom.js", "pmjson.js", "tools.js", "xmlhttp.js", "dtree.js", "jquery/jquery-latest.pack.js", "jquery/jqpmapper.js", "jquery/dimensions.js");

header("Content-type: text/html; charset=$defCharset");

$infoWin = $_SESSION['infoWin'];
$alignQueryResults = $_SESSION['alignQueryResults'];

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $gLanguage ?>" xml:lang="<?php echo $gLanguage ?>">

<head>
<title><?php echo (_p("Query Results")) ?></title>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/common.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/sorttable.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/custom.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/pmjson.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/xmlhttp.js"></script>

 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/jquery/jquery-latest.pack.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/jquery/jquery.compat-1.0.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/jquery/jquery.pmapper.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/jquery/jquery.dimensions.js"></script>
 <script type="text/javascript" src="<?php echo $_SESSION['PM_JAVASCRIPT'] ?>/jquery/jquery.treeview.pack.js"></script>
 <script type="text/javascript" src="<?php echo ($_SESSION['PM_INCPHP_LOCATION'] . "/js_custom.php?" . SID) ?>"></script>

 <script type="text/javascript">
    var SID = '<?php echo SID ?>';
    var resultJSON = <?php  echo $_SESSION['JSON_Results']; ?>;
    var infoWin = '<?php echo $infoWin ?>';
    
 </script>
 
 <link rel="stylesheet" href="templates/default.css" type="text/css" />
 <link rel="stylesheet" href="templates/query.css" type="text/css" />
 <link rel="stylesheet" href="templates/treeview.css" type="text/css" />
</head>

<body  id="infoZone" class="pmInfo" onload="writeQResult(resultJSON, infoWin); window.focus(); <?php if ($alignQueryResults) echo "ts_alignTables();" ?> ">


<div id="queryResult"></div>

</body>
</html>
